venn-beta
    set A["Git"] : 6
        text version_control ["Version control"]
    set B["Mermaid"] : 6
        text diagramming ["Diagramming"]
    union A,B : 2
        text docs_automation ["Docs automation"]
